### PR TITLE
Fix Cppcheck issues

### PR DESCRIPTION
**Pull request by ychernysheva**
Fixes #[6723](https://adc.luxoft.com/jira/browse/FORDTCN-6723)

This PR is **not ready** for review.

### Risk
This PR makes **no** API changes.

### Summary
Fix errors, detected by Cppcheck.

Used settings:
cppcheck --std=c++11 --enable=all --inconclusive --suppress=missingInclude  --suppress=syntaxError  --inline-suppr -i "src/3rd_party-static" -i "src/3rd_party" --xml --xml-version=2 -q sdl_core/src 2> cppcheck.xml

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by Ypostolov** [comment]
`--suppress=missingInclude --suppress=syntaxError`
 Using  these flags in the settings, will accumulate errors of this type without fixing them.

**Comment by ychernysheva** [comment]
@Ypostolov In this case flags --suppress=missingInclude and --suppress=syntaxError are necessary, because this errors are false positive (there are no syntax errors, received warnings are triggered by incorrect parsing of gtest macro in several unit tests, and there is no way to fix this problem in adequate way, because it's a problem of cppcheck).

**Comment by Ypostolov** [comment]
@ychernysheva 
Using flags --suppress=missingInclude --suppress=syntaxError, we completely remove the check for these types of errors, we can suppress errors when they are false positive.

**Comment by VladSemenyuk** [comment]
Now we have syntaxErorr only on Google Test Macros. I think that supressing this errors for before every test is't very pretty solution. This problem should be solved in future when we will add cppcheck on git hooks in some other way. This task was to fix real errors.

**Pull request closed without merging**
